// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFazendaSerrana.Models.Context;

namespace WebFazendaSerrana.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20191002145608_MIGRATION3")]
    partial class MIGRATION3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebFazendaSerrana.Models.Agrotoxico", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int>("QtdDisponivel");

                    b.Property<int>("UnidadeMedida");

                    b.HasKey("Codigo");

                    b.ToTable("TB_AGROTOXICO");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.AplicarAgrotoxico", b =>
                {
                    b.Property<int>("IdAplicarAgrotoxico")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoAgrotoxico");

                    b.Property<int>("CodigoPraga");

                    b.Property<int>("NumeroAreaPlantio");

                    b.Property<int>("QtdAplicado");

                    b.Property<string>("Tipo");

                    b.HasKey("IdAplicarAgrotoxico");

                    b.HasIndex("CodigoAgrotoxico");

                    b.HasIndex("CodigoPraga");

                    b.HasIndex("NumeroAreaPlantio");

                    b.ToTable("TB_APLICAR_AGROTOXICO");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.AreaPlantio", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCultura");

                    b.Property<DateTime>("DataPlantio");

                    b.Property<int>("IdMatricula");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tamanho");

                    b.HasKey("Numero");

                    b.HasIndex("CodigoCultura");

                    b.HasIndex("IdMatricula");

                    b.ToTable("TB_AREAPLANTIO");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.AuxiliarAgrotoxico", b =>
                {
                    b.Property<int>("CodigoAgrotoxico");

                    b.Property<int>("CodigoPraga");

                    b.HasKey("CodigoAgrotoxico", "CodigoPraga");

                    b.HasIndex("CodigoPraga");

                    b.ToTable("TB_AUXILIAR_AGROTOXICO");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.Cultura", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MesFinal");

                    b.Property<string>("MesIdeal");

                    b.Property<string>("Nome");

                    b.Property<DateTime>("TempoMaximo")
                        .HasColumnType("datetime2");

                    b.HasKey("Codigo");

                    b.ToTable("TB_CULTURA");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.Funcionario", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome");

                    b.HasKey("Matricula");

                    b.ToTable("TB_FUNCIONARIO");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.Praga", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataUltimaPraga")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstacaoAno");

                    b.Property<string>("NomeCientifico");

                    b.Property<string>("NomePopular");

                    b.HasKey("Codigo");

                    b.ToTable("TB_PRAGA");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.TipoCultura", b =>
                {
                    b.Property<int>("CodigoCultura");

                    b.Property<int>("CodigoPraga");

                    b.HasKey("CodigoCultura", "CodigoPraga");

                    b.HasIndex("CodigoPraga");

                    b.ToTable("TB_TIPOCULTURA");
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.AplicarAgrotoxico", b =>
                {
                    b.HasOne("WebFazendaSerrana.Models.Agrotoxico", "Agrotoxico")
                        .WithMany("ListaAplicarAgrotoxicos")
                        .HasForeignKey("CodigoAgrotoxico")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFazendaSerrana.Models.Praga", "Praga")
                        .WithMany("ListaAplicarAgrotoxicos")
                        .HasForeignKey("CodigoPraga")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFazendaSerrana.Models.AreaPlantio", "AreaPlantio")
                        .WithMany("ListaAplicarAgrotoxicos")
                        .HasForeignKey("NumeroAreaPlantio")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.AreaPlantio", b =>
                {
                    b.HasOne("WebFazendaSerrana.Models.Cultura", "Cultura")
                        .WithMany("ListaAreaPlantios")
                        .HasForeignKey("CodigoCultura")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFazendaSerrana.Models.Funcionario", "Funcionario")
                        .WithMany("ListaAreaPlantios")
                        .HasForeignKey("IdMatricula")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.AuxiliarAgrotoxico", b =>
                {
                    b.HasOne("WebFazendaSerrana.Models.Agrotoxico", "Agrotoxico")
                        .WithMany("ListaAuxiliarAgrotoxicos")
                        .HasForeignKey("CodigoAgrotoxico")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFazendaSerrana.Models.Praga", "Praga")
                        .WithMany("ListaAuxiliarAgrotoxicos")
                        .HasForeignKey("CodigoPraga")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebFazendaSerrana.Models.TipoCultura", b =>
                {
                    b.HasOne("WebFazendaSerrana.Models.Cultura", "Cultura")
                        .WithMany("ListaTipoCulturas")
                        .HasForeignKey("CodigoCultura")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebFazendaSerrana.Models.Praga", "Praga")
                        .WithMany("ListaTipoCulturas")
                        .HasForeignKey("CodigoPraga")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
